# Generated by Django 4.2.5 on 2023-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='costumer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='photographer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
