# Generated by Django 4.2.5 on 2023-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_image_costumer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='heart',
            field=models.BooleanField(default=False),
        ),
    ]
