# Generated by Django 4.2.5 on 2023-09-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_image_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
