# Generated by Django 4.2.5 on 2023-09-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_image_sequence_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='html_name',
            field=models.CharField(default='TOepF', max_length=8),
        ),
    ]
