# Generated by Django 4.2.5 on 2023-09-07 21:40

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_remove_album_html_name_album_http_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_image_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='http_name',
            field=models.CharField(default=album.models.generate_html_name, max_length=8),
        ),
    ]
