# Generated by Django 4.2.5 on 2023-09-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_image_album_image_id_alter_album_http_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album_image_id',
            field=models.IntegerField(blank=True),
        ),
    ]
